### ISSUE TITLE
Add maven-source-plugin

### ISSUE THREAD

**Issue by bjoernhaeuser** [rebuy-de/consul-java-client#15]
Sources are currently missing on maven, we need to add the `maven-source-plugin` configuration

**Comment by ghost** [comment]
will add it

**Comment by ghost** [comment]
http://maven.dc1.rebuy/repository/com/rebuy/consul-java-client/1.2.0/ sources are deployed and the maven source plugin is also configured https://github.com/rebuy-de/consul-java-client/blob/master/pom.xml#L44 @bjoernhaeuser

**Comment by bjoernhaeuser** [comment]
Oh sorry

**Comment by bjoernhaeuser** [comment]
oh sorry
