### ISSUE TITLE
Add logger

### ISSUE THREAD

**Issue by svenwltr** [rebuy-de/consul-java-client#9]
Log registering, unregistering and shutdown hook activation.

**Comment by ghost** [comment]
aren't we already doing that?

**Comment by svenwltr** [comment]
Nope: https://github.com/rebuy-de/consul-java-client/blob/master/src/main/java/com/rebuy/consul/ConsulService.java

That's why we have to: https://github.com/rebuy-de/warehouse-silo/blob/master/silo/src/main/java/com/rebuy/service/warehouse/silo/service/ConsulRegistrationService.java#L25
